[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
  ESP32Async/ESPAsyncWebServer@^3.6.0
  ESP32Async/AsyncTCP@^3.3.2
  bblanchon/ArduinoJson@^6.21.2
  knolleary/PubSubClient@^2.8
build_flags = 
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=5
monitor_speed = 115200
board_build.filesystem = littlefs